# Generated by Django 2.2.1 on 2019-05-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products_app', '0003_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start_bid', models.FloatField(default=0.0)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
