# Generated by Django 2.2.1 on 2019-05-15 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_delete_item'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auction_app', '0003_delete_bid'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
