# Generated by Django 2.2.1 on 2019-05-15 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0002_auto_20190515_0751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
