# Generated by Django 2.2.1 on 2019-05-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auction_app', '0003_delete_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_bid', models.FloatField()),
                ('is_closed', models.BooleanField(default=False)),
            ],
        ),
    ]
